version: '3.8'

services:
  app:
    build:
      context: .  # Use the current directory for the build context
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - LIQUIBASE_CHANGELOG=${LIQUIBASE_CHANGELOG}
      - LIQUIBASE_ENABLED=${LIQUIBASE_ENABLED}
      - JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL}
      - JPA_OPEN_IN_VIEW=${JPA_OPEN_IN_VIEW}
      - JPA_PROPERTIES_HIBERNATE_DIALECT=${JPA_PROPERTIES_HIBERNATE_DIALECT}
      - JPA_PROPERTIES_JDBC_TIMEZONE=${JPA_PROPERTIES_JDBC_TIMEZONE}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: lynxie
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME}" ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"