name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch
  pull_request:
    branches:
      - main  # Optionally, run this action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 22 with specific distribution
      - name: Set up JDK 22 (AdoptOpenJDK)
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'  # Options: 'adopt', 'zulu', 'temurin', 'corretto', etc.

      # Step 3: Grant execute permission to gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build the JAR file
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Log in to Docker Hub (add secrets in GitHub settings)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lynxie-api-dev:latest .

      # Step 7: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lynxie-api-dev:latest
